name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.event_name == 'pull_request' }}
      - name: Check & assemble
        run: ./gradlew --stacktrace check assembleDebug
      - name: Upload ktlint SARIF (if present)
        if: ${{ hashFiles('**/build/reports/ktlint/**/*.sarif') != '' }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "**/build/reports/ktlint/**/*.sarif"

      - name: Upload detekt SARIF (if present)
        if: ${{ hashFiles('**/build/reports/detekt/**/*.sarif') != '' }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "**/build/reports/detekt/**/*.sarif"
